classroom_id: "test_classroom_id_0",
classroom_title: {
  content_id: "classroom_title",
  html: "Maths"
},
thumbnail_bg_color: "#00FFFFFF",
thumbnail_filename: "",
topic_prerequisites: {
  GJ2rLXRKD5hw: ["test_topic_id_0", "test_topic_id_1"],
  omzF4oqgeTXd: []
},
topic_ids: ["GJ2rLXRKD5hw", "GJ2rLXRKD5hw"]
